const {l} = require("../utils/utils");
const {stripe_api} = require('../config.json')
const stripe = require('stripe')(`${stripe_api.secret_key}`);

/**
 * Transfers an amount to a stripe account from main account's balance.
 *
 * @param {double} amount The amount to transfer in AUD.
 * @param {string} accountID The ID of the Stripe account to transfer to.
 */
async function transfer(amount, accountID){
    // Convert amount to cents as Stripe handles payments using cents.
    const amountInCents = amount * 100;

    return await stripe.transfers.create({
        amount: amountInCents,
        currency: 'aud',
        destination: accountID
    });
}

/**
 * Verifies that a request was made by Stripe.
 *
 * More details: https://stripe.com/docs/webhooks/signatures
 *
 * @param {object} request The request.
 * @param {string} endpointSecret Endpoint Secret generated by Stripe for webhooks.
 */
async function verifyWebhook(request, endpointSecret){
    // Get the signature sent by Stripe
    const signature = request.headers['stripe-signature'];
    try {
        return await stripe.webhooks.constructEvent(
            request.body,
            signature,
            endpointSecret
        );
    } catch (e) {
        l(`Webhook signature verification failed: ${e.message}`);
        return null;
    }
}

module.exports = {transfer, verifyWebhook}
